language: emacs-lisp
before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - curl -fsSkL https://raw.github.com/rejeep/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install emacs-24.3-bin
  - evm install $EVM_EMACS --use
  - cask
  - EMACS=$(evm bin emacs-24.3-bin)
env:
  - EVM_EMACS=emacs-23.4-bin
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
script:
  - emacs --version
  - make
